//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Semana_6_Oliver_1100292_Part2.WS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Caso", Namespace="http://oliver.org/")]
    [System.SerializableAttribute()]
    public partial class Caso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaCasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicasionCasoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalleCasoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TipoCaso {
            get {
                return this.TipoCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCasoField, value) != true)) {
                    this.TipoCasoField = value;
                    this.RaisePropertyChanged("TipoCaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FechaCaso {
            get {
                return this.FechaCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaCasoField, value) != true)) {
                    this.FechaCasoField = value;
                    this.RaisePropertyChanged("FechaCaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string UbicasionCaso {
            get {
                return this.UbicasionCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicasionCasoField, value) != true)) {
                    this.UbicasionCasoField = value;
                    this.RaisePropertyChanged("UbicasionCaso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DetalleCaso {
            get {
                return this.DetalleCasoField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalleCasoField, value) != true)) {
                    this.DetalleCasoField = value;
                    this.RaisePropertyChanged("DetalleCaso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://oliver.org/")]
    [System.SerializableAttribute()]
    public partial class Respuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        private int TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://oliver.org/")]
    [System.SerializableAttribute()]
    public partial class Persona : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CedulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        private int IdCasoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Cedula {
            get {
                return this.CedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.CedulaField, value) != true)) {
                    this.CedulaField = value;
                    this.RaisePropertyChanged("Cedula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int IdCaso {
            get {
                return this.IdCasoField;
            }
            set {
                if ((this.IdCasoField.Equals(value) != true)) {
                    this.IdCasoField = value;
                    this.RaisePropertyChanged("IdCaso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://oliver.org/", ConfigurationName="WS.MyWSSoap")]
    public interface MyWSSoap {
        
        // CODEGEN: Generating message contract since element name caso from namespace http://oliver.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://oliver.org/RegistroCaso", ReplyAction="*")]
        Semana_6_Oliver_1100292_Part2.WS.RegistroCasoResponse RegistroCaso(Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://oliver.org/RegistroCaso", ReplyAction="*")]
        System.Threading.Tasks.Task<Semana_6_Oliver_1100292_Part2.WS.RegistroCasoResponse> RegistroCasoAsync(Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequest request);
        
        // CODEGEN: Generating message contract since element name persona from namespace http://oliver.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://oliver.org/RegistroPersona", ReplyAction="*")]
        Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaResponse RegistroPersona(Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://oliver.org/RegistroPersona", ReplyAction="*")]
        System.Threading.Tasks.Task<Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaResponse> RegistroPersonaAsync(Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroCasoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroCaso", Namespace="http://oliver.org/", Order=0)]
        public Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequestBody Body;
        
        public RegistroCasoRequest() {
        }
        
        public RegistroCasoRequest(Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://oliver.org/")]
    public partial class RegistroCasoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Semana_6_Oliver_1100292_Part2.WS.Caso caso;
        
        public RegistroCasoRequestBody() {
        }
        
        public RegistroCasoRequestBody(Semana_6_Oliver_1100292_Part2.WS.Caso caso) {
            this.caso = caso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroCasoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroCasoResponse", Namespace="http://oliver.org/", Order=0)]
        public Semana_6_Oliver_1100292_Part2.WS.RegistroCasoResponseBody Body;
        
        public RegistroCasoResponse() {
        }
        
        public RegistroCasoResponse(Semana_6_Oliver_1100292_Part2.WS.RegistroCasoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://oliver.org/")]
    public partial class RegistroCasoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Semana_6_Oliver_1100292_Part2.WS.Respuesta RegistroCasoResult;
        
        public RegistroCasoResponseBody() {
        }
        
        public RegistroCasoResponseBody(Semana_6_Oliver_1100292_Part2.WS.Respuesta RegistroCasoResult) {
            this.RegistroCasoResult = RegistroCasoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroPersona", Namespace="http://oliver.org/", Order=0)]
        public Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequestBody Body;
        
        public RegistroPersonaRequest() {
        }
        
        public RegistroPersonaRequest(Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://oliver.org/")]
    public partial class RegistroPersonaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Semana_6_Oliver_1100292_Part2.WS.Persona persona;
        
        public RegistroPersonaRequestBody() {
        }
        
        public RegistroPersonaRequestBody(Semana_6_Oliver_1100292_Part2.WS.Persona persona) {
            this.persona = persona;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegistroPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegistroPersonaResponse", Namespace="http://oliver.org/", Order=0)]
        public Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaResponseBody Body;
        
        public RegistroPersonaResponse() {
        }
        
        public RegistroPersonaResponse(Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://oliver.org/")]
    public partial class RegistroPersonaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Semana_6_Oliver_1100292_Part2.WS.Respuesta RegistroPersonaResult;
        
        public RegistroPersonaResponseBody() {
        }
        
        public RegistroPersonaResponseBody(Semana_6_Oliver_1100292_Part2.WS.Respuesta RegistroPersonaResult) {
            this.RegistroPersonaResult = RegistroPersonaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWSSoapChannel : Semana_6_Oliver_1100292_Part2.WS.MyWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWSSoapClient : System.ServiceModel.ClientBase<Semana_6_Oliver_1100292_Part2.WS.MyWSSoap>, Semana_6_Oliver_1100292_Part2.WS.MyWSSoap {
        
        public MyWSSoapClient() {
        }
        
        public MyWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Semana_6_Oliver_1100292_Part2.WS.RegistroCasoResponse Semana_6_Oliver_1100292_Part2.WS.MyWSSoap.RegistroCaso(Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequest request) {
            return base.Channel.RegistroCaso(request);
        }
        
        public Semana_6_Oliver_1100292_Part2.WS.Respuesta RegistroCaso(Semana_6_Oliver_1100292_Part2.WS.Caso caso) {
            Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequest inValue = new Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequest();
            inValue.Body = new Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequestBody();
            inValue.Body.caso = caso;
            Semana_6_Oliver_1100292_Part2.WS.RegistroCasoResponse retVal = ((Semana_6_Oliver_1100292_Part2.WS.MyWSSoap)(this)).RegistroCaso(inValue);
            return retVal.Body.RegistroCasoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Semana_6_Oliver_1100292_Part2.WS.RegistroCasoResponse> Semana_6_Oliver_1100292_Part2.WS.MyWSSoap.RegistroCasoAsync(Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequest request) {
            return base.Channel.RegistroCasoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Semana_6_Oliver_1100292_Part2.WS.RegistroCasoResponse> RegistroCasoAsync(Semana_6_Oliver_1100292_Part2.WS.Caso caso) {
            Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequest inValue = new Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequest();
            inValue.Body = new Semana_6_Oliver_1100292_Part2.WS.RegistroCasoRequestBody();
            inValue.Body.caso = caso;
            return ((Semana_6_Oliver_1100292_Part2.WS.MyWSSoap)(this)).RegistroCasoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaResponse Semana_6_Oliver_1100292_Part2.WS.MyWSSoap.RegistroPersona(Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequest request) {
            return base.Channel.RegistroPersona(request);
        }
        
        public Semana_6_Oliver_1100292_Part2.WS.Respuesta RegistroPersona(Semana_6_Oliver_1100292_Part2.WS.Persona persona) {
            Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequest inValue = new Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequest();
            inValue.Body = new Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequestBody();
            inValue.Body.persona = persona;
            Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaResponse retVal = ((Semana_6_Oliver_1100292_Part2.WS.MyWSSoap)(this)).RegistroPersona(inValue);
            return retVal.Body.RegistroPersonaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaResponse> Semana_6_Oliver_1100292_Part2.WS.MyWSSoap.RegistroPersonaAsync(Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequest request) {
            return base.Channel.RegistroPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaResponse> RegistroPersonaAsync(Semana_6_Oliver_1100292_Part2.WS.Persona persona) {
            Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequest inValue = new Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequest();
            inValue.Body = new Semana_6_Oliver_1100292_Part2.WS.RegistroPersonaRequestBody();
            inValue.Body.persona = persona;
            return ((Semana_6_Oliver_1100292_Part2.WS.MyWSSoap)(this)).RegistroPersonaAsync(inValue);
        }
    }
}
